language: go
go_import_path: go-ratelimit
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

go:
 - master 

install:
  - make setup

script:
   - make
